# Generated by Django 5.0.3 on 2024-03-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblCandidates',
        ),
        migrations.DeleteModel(
            name='TblElectCandidates',
        ),
        migrations.DeleteModel(
            name='TblPosition',
        ),
        migrations.DeleteModel(
            name='TblVoter',
        ),
        migrations.DeleteModel(
            name='TblVotes',
        ),
    ]
