# Generated by Django 5.0.3 on 2024-03-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
